[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "mkdir -p build && cp -r src build/ && cp -r index.html package.json build/"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
